spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - in-cluster
                - cluster-local
  template:
    metadata:
      name: 'my-app-{{name}}'
    spec:
      destination:
        namespace: autoscaling-poc
        server: '{{server}}'
      ignoreDifferences:
        - group: apps
          jsonPointers:
            - /metadata/labels
          kind: Deployment
      project: default
      source:
        path: 'app/overlays/{{name}}'
        repoURL: 'https://github.com/wanghongtao007/cloudburst.git'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
